<?php
/**
 * @var $block \Monogo\QrCode\Block\QrCode\View
 */

$product = $block->getProduct();
$qrCode = $product->getQrcodeData();
$productName = $product->getName();
?>

<?php if ($qrCode && $block->isBase64Image($qrCode)): ?>
    <div class="qr-code-wrap">
        <img class="qr-code" src="data:image/png;base64,<?= $qrCode ?>" alt="<?= $productName ?>"
             title="<?= $productName ?>"/>
    </div>
<?php endif; ?>
